steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/mytrade-repo/mytrade:latest',
      '.'
    ]

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/mytrade-repo/mytrade:latest'
    ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mytrade-repo/mytrade:latest'

timeout: 1200s